apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # specifies the path to each required policy 
  - ../policies/ControllerContainerAllowingPrivilegeEscalation/policy.yaml
  - ../policies/ControllerContainerBlockHostPath/policy.yaml
  - ../policies/ControllerContainerRunningAsRoot/policy.yaml