apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # specifies the path to each required policy 
  - ../policies/ControllerContainerAllowingPrivilegeEscalation/policy.yaml
  - ../policies/ControllerContainerLinuxCapabilities/policy.yaml
  - ../policies/ControllerContainerRunningPrivilegedMode/policy.yaml
  - ../policies/ControllerContainerServiceAccountTokenAutomount/policy.yaml
  - ../policies/ControllerImageTag/policy.yaml
  - ../policies/ControllerMinimumReplicaCount/policy.yaml
  - ../policies/ControllerProhibitNamespace/policy.yaml
  - ../policies/ControllerSeccompRuntimeDefault/policy.yaml
  - ../policies/ControllerTolerations/policy.yaml
  - ../policies/PersistentVolumeReclaimPolicy/policy.yaml
  - ../policies/RBACClusterRoleClusterAdmin/policy.yaml
  - ../policies/ServiceAccountDisableTokenAutomount/policy.yaml
  - ../policies/ServiceRestrictProtocols/policy.yaml